###############################################################################
# quilc-tests docker image
###############################################################################
FROM quilc-base

# load quilc-tests system
WORKDIR /src/quilc
RUN sbcl --eval "(ql:quickload :quilc-tests)" --quit

# executed on docker run
ENTRYPOINT ["make", "test", "test-ccl"]
