###############################################################################
# quilc-base Docker image
###############################################################################
FROM rigetticomputing/lisp-base:qcs-1.2.0

# organize the source
ADD quilc /src/quilc

ARG build_target

# build quilc
WORKDIR /src/quilc
RUN sbcl --eval "(ql:quickload :quilc)" --quit
RUN make ${build_target}
