###############################################################################
# quilc docker image (docker.lab.rigetti.com/qcs/quilc)
###############################################################################
FROM quilc-base

# executed on docker run
ENTRYPOINT ["./quilc"]
