.TH QUILC 1 "24 September 2018" "0.13.0 (cl-quil: 0.19.0) [e9b41e3]" 
.SH NAME
quilc \- an optimizing, architecture independent Quil compiler
.SH SYNOPSIS

quilc <options>

.SH DESCRIPTION
todo
.SH OPTIONS
.IP "-S, --server"
(Server Mode) Run the compiler in Server Mode. This starts an HTTP server.
.IP "-h, --help"
Show the help message.
.IP "-v, --version"
Show the version.
.SH EXAMPLES
quilc --isa "8Q" < file.quil
.RS
Compile a Quil file (printing the result to stdout) for an eight qubit ring.
.RE

.SH SUPPORT
Contact <support@rigetti.com> or Robert Smith <robert@rigetti.com>.
.SH COPYRIGHT
Copyright (c) 2018 Rigetti Computing
.SH SEE ALSO
qvm(1)
