name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-cl-quil:
    name: Test cl-quil
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script - test-cl-quil
        run: |
          sudo apt install sbcl
          mkdir -p ${HOME}/quicklisp/local-projects
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/magicl.git
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/qvm.git
          make quicklisp
          sudo make install-test-deps
          make test-cl-quil

  test-quilc:
    name: Test quilc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script - test-quilc
        run: |
          sudo apt install sbcl
          mkdir -p ${HOME}/quicklisp/local-projects
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/magicl.git
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/qvm.git
          make quicklisp
          sudo make install-test-deps
          make test-quilc

  test-quilt:
    name: Test quilt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script - test-quilt
        run: |
          sudo apt install sbcl
          mkdir -p ${HOME}/quicklisp/local-projects
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/magicl.git
          git -C ${HOME}/quicklisp/local-projects clone https://github.com/quil-lang/qvm.git
          make quicklisp
          sudo make install-test-deps
          make test-quilt
